#!/usr/bin/env php
<?php
declare(strict_types = 1);

$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__ . '/../../../vendor/autoload.php',
];

foreach ($paths as $file) {
    if (file_exists($file)) {
        require $file;
        break;
    }
}

use function Innmind\Kalmiya\cli;
use Innmind\Kalmiya\HttpTransport\RetryOnNotFound;
use Innmind\CLI\Framework\{
    Application,
    Main,
};
use Innmind\Url\Path;

new class extends Main {
    protected function configure(Application $app): Application
    {
        return $app
            ->configAt(Path::of(__DIR__.'/config/'))
            ->useResilientOperatingSystem()
            ->commands(static fn($env, $os): array => cli(
                $os->filesystem()->mount(Path::of(
                    $env->variables()->get('HOME').'/.kalmiya/',
                )),
                new RetryOnNotFound(
                    $os->remote()->http(),
                    $os->process(),
                ),
                $os->clock(),
                $os->sockets(),
            ));
    }
};
